export const contactConstants = {

    GET_ALL_CONTACT_REQUEST : 'GET_ALL_CONTAT_REQUEST',
    GET_ALL_CONTACT_SUCCESS : 'GET_ALL_CONTAT_SUCCESS ',
    GET_ALL_CONTACT_FAILURE : 'GET_ALL_CONTAT_FAILURE ',

    ADD_CONTACT_REQUEST : 'ADD_CONTACT_REQUEST',
    ADD_CONTACT_SUCCESS : 'ADD_CONTACT_SUCCESS',
    ADD_CONTACT_FAILURE : 'ADD_CONTACT_FAILURE',


}

